name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0
  trabalhos:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.16.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
