// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyxk680vyPmqMQ3VbKgGo-Hf34USxhRG8',
    appId: '1:447974650971:web:955930eb50a4689ffbbb7e',
    messagingSenderId: '447974650971',
    projectId: 'ddm-alunos',
    authDomain: 'ddm-alunos.firebaseapp.com',
    storageBucket: 'ddm-alunos.firebasestorage.app',
    measurementId: 'G-NN43RFQTL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLzNWTlNjkzcCo19db2eKWkxfHyWcesgI',
    appId: '1:447974650971:android:581cad9da4de001bfbbb7e',
    messagingSenderId: '447974650971',
    projectId: 'ddm-alunos',
    storageBucket: 'ddm-alunos.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyxk680vyPmqMQ3VbKgGo-Hf34USxhRG8',
    appId: '1:447974650971:web:d406058b368ad644fbbb7e',
    messagingSenderId: '447974650971',
    projectId: 'ddm-alunos',
    authDomain: 'ddm-alunos.firebaseapp.com',
    storageBucket: 'ddm-alunos.firebasestorage.app',
    measurementId: 'G-T7FG8XG11D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTz0uvEANGjHTwYblNVWRa6wjTjeFcP6k',
    appId: '1:447974650971:ios:98b39ba8e0db1e11fbbb7e',
    messagingSenderId: '447974650971',
    projectId: 'ddm-alunos',
    storageBucket: 'ddm-alunos.firebasestorage.app',
    iosClientId: '447974650971-sdm3rhfap6emnbg6qpfvkalubirldhgb.apps.googleusercontent.com',
    iosBundleId: 'org.ddm25.app',
  );

}